### ISSUE TITLE
additional resources 

### ISSUE THREAD

**Issue by yina-quique** [rbcavanaugh/csd-stats#3]
**Learning R.** 
- Datacamp was a good starting point; you can choose courses specific to your needs. It is not free, though. 

**Bayesian statistics**
- Statistical Rethinking lectures by Richard McElreath 
   Lectures: https://github.com/rmcelreath/stat_rethinking_2022
  YouTube channel of the lectures: https://www.youtube.com/watch?v=cclUd_HoRlo

**Comment by william-streicher-evans** [comment]
Thank you for pulling together all of these excellent resources! You should add your published resources for completing reproducible small N research, especially since it provides a nice model that pulls together many of the things from the resources you've already provided: 
- https://rb-cavanaugh.shinyapps.io/reproducible-small-N/
- https://osf.io/7fp3x/
- https://robcavanaugh.com/images/cavanaugh2022-reproducibility.pdf
